import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/_mycomponents/navigation/MainNavbar";
import ReduxStoreProvider from "@/_mycomponents/providers/ReduxStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Funeral",
  description: "Generated by create next app",
};
// -- props -- //
type Props = Readonly<{
  children: React.ReactNode;
}>;
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className + " dark:bg-[#111423]"}>
        <ReduxStoreProvider>
          <MainNavbar />
          {children}
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
